version: '3'
services:
  multiplealignment-multiple-dash:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: multiplealignment-multiple-dash
    volumes:
      - ./logs:/app/logs:rw
      - ./temp:/app/temp:rw
    networks:
      - default
      - nginx-net
    restart: unless-stopped
    command: /app/run_server.sh
    environment:
      VIRTUAL_HOST: multiplealignment.gnps2.org
      VIRTUAL_PORT: 5000
      LETSENCRYPT_HOST: multiplealignment.gnps2.org
      LETSENCRYPT_EMAIL: mwang87@gmail.com
    deploy:
      resources:
        limits:
          memory: 8000M

networks:
  nginx-net:
    external:
      name: nginx-net